fix: remove libheif-freeworld from packages to fix build
This is probably temporary until rpmfusion sorts things out but this is
to fix all Fedora 38 builds failing with:

error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package libheif-freeworld-1.15.1-4.fc38.x86_64 from rpmfusion-free requires libheif(x86-64) = 1.15.1, but none of the providers can be installed
  - package libheif-freeworld-1.16.1-1.fc38.x86_64 from rpmfusion-free-updates requires libheif(x86-64) = 1.16.1, but none of the providers can be installed
  - cannot install both libheif-1.15.1-2.fc38.x86_64 from fedora and libheif-1.16.2-1.fc38.x86_64 from @System
  - cannot install both libheif-1.16.1-1.fc38.x86_64 from updates-archive and libheif-1.16.2-1.fc38.x86_64 from @System